spring:
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: jhpark0418